### ISSUE TITLE
Add support for all (zero, two, few, many, other) plural format options

### ISSUE THREAD

**Issue by artemjackson** [en-japan-air/react-intl-formatted-duration#3]
First, thank you for the good package.

Second, I've faced with an issue when some languages (e.g. Russian, Ukrain) have "one", "few" and "many" plural format options for days formating. So the `react-intl-formatted-duration.daysPlural` and `react-intl-formatted-duration.daysSingular` that the package provides is not enought for such languages.

Please add support for all available plural format options.

P.S. I can provide a PR if needed.

**Comment by piuccio** [comment]
thanks for the interest in this package.

If you can provide a PR I'd appreciate it, it would speed up things as I'm not very familiar with those languages.
It's also fine if you can post here a test case resembling one of the [unit tests](https://github.com/en-japan-air/react-intl-formatted-duration/blob/master/__tests__/extended-format.test.js)

**Comment by piuccio** [comment]
@artemjackson it took a while but version `2.0.0` has now proper support for all plural formats
