### ISSUE TITLE
Support for formatDuration?

### ISSUE THREAD

**Issue by Ephys** [en-japan-air/react-intl-formatted-duration#4]
Good morning :)

`react-intl` provides methods on the `intl` object such as `formatMessage` as an alternative to `FormattedMessage` which does not generate a react component.

Would you be interested in a PR to export a new method `formatDuration(intl, duration, options)` ?

Thank you!

**Comment by piuccio** [comment]
Yeah sure that'll be great

**Comment by piuccio** [comment]
#15 split this package in two.
I've created a separate, generic, package [intl-unofficial-duration-unit-format](https://github.com/en-japan-air/intl-unofficial-duration-unit-format) that only converts seconds into tokens, it does not depend on `react` or `react-intl` so it can be used in any other project.
This package now is just a small react wrapper that delegates to the former.

Let me know if this is enough or if we should export `formatDuration` from this package as well
